apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vanyaai-data
  namespace: vanyaai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # storageClassName: standard   # set to your cloud's class if needed
